query Recipes {
	recipes {
		...RecipeDetails
	}
}

mutation CreateRecipe($recipe: RecipeInput!, $imageId: ID) {
	createRecipe(recipe: $recipe, imageId: $imageId) {
		...RecipeDetails
	}
}

mutation UpdateRecipe($id: ID!, $recipe: RecipeInput!, $imageId: ID) {
	updateRecipe(id: $id, recipe: $recipe, imageId: $imageId) {
		...RecipeDetails
	}
}

mutation CreateImageUpload($contentType: String!) {
	createImageUpload(contentType: $contentType) {
		key
		uploadUrl
	}
}

mutation DeleteRecipe($id: ID!) {
	deleteRecipe(id: $id)
}

mutation RecipeCooked($id: ID!, $date: Date!) {
	recipeCooked(id: $id, date: $date) {
		...RecipeDetails
	}
}

mutation DeleteRecipeCooked($recipeId: ID!, $cookedId: ID!) {
  deleteRecipeCooked(recipeId: $recipeId, cookedId: $cookedId) {
    ...RecipeDetails
  }
}

fragment RecipeDetails on Recipe {
	id
	title
	imageUrl
	directions
	sideDish
	preparationTime
	servingCount
	tags
	ingredients {
		id
		name
		isGroup
		amount
		amountUnit
	}
	cookedHistory {
    id
		date
		user {
			id
			displayName
		}
	}
}
